# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import json
import argparse
import pandas as pd
import xml.etree.ElementTree as ET

# ---------------- XML helpers (namespace-safe) ----------------
def _lname(tag: str) -> str:
    return tag.split("}", 1)[-1] if "}" in tag else tag

def _find_first_by_local_name(root: ET.Element, wanted: str):
    for e in root.iter():
        if _lname(e.tag) == wanted:
            return e
    return None

# ---------------- XML subtree -> nested python object ----------------
def xml_to_obj(elem: ET.Element):
    """
    Element -> nested structure:
      - dict for elements with children/attrs
      - str for leaf text
      - list for repeated sibling tags
    Attributes stored as "@attr".
    """
    obj = {}

    # attributes
    for k, v in (elem.attrib or {}).items():
        obj[f"@{_lname(k)}"] = v

    children = list(elem)
    if children:
        grouped = {}
        for c in children:
            k = _lname(c.tag)
            grouped.setdefault(k, []).append(xml_to_obj(c))

        for k, vals in grouped.items():
            obj[k] = vals[0] if len(vals) == 1 else vals

        txt = (elem.text or "").strip()
        if txt:
            obj["#text"] = txt
        return obj

    # leaf
    txt = (elem.text or "").strip()
    if obj:
        if txt:
            obj["#text"] = txt
        return obj
    return txt

def flatten_obj(obj, parent_key="", sep="__"):
    """
    Nested dict/list -> single-level dict for a wide DataFrame.
    Lists become indexed columns: Foo__0__Bar, Foo__1__Bar, ...
    """
    items = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            nk = f"{parent_key}{sep}{k}" if parent_key else k
            items.update(flatten_obj(v, nk, sep=sep))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            nk = f"{parent_key}{sep}{i}" if parent_key else str(i)
            items.update(flatten_obj(v, nk, sep=sep))
    else:
        if parent_key:
            items[parent_key] = obj
    return items

# ---------------- Directory scan + parsing ----------------
def iter_xml_files(input_dir: str):
    for dirpath, _, filenames in os.walk(input_dir):
        for fn in filenames:
            if fn.lower().endswith(".xml"):
                yield os.path.join(dirpath, fn)

def parse_return_header_row(xml_path: str) -> dict:
    root = ET.parse(xml_path).getroot()
    rh = _find_first_by_local_name(root, "ReturnHeader")

    row = {"source_file": xml_path}

    if rh is None:
        row["has_return_header"] = False
        return row

    rh_obj = xml_to_obj(rh)
    flat = flatten_obj(rh_obj, parent_key="ReturnHeader")

    # Keep both: wide columns + original nested JSON (useful for re-processing)
    row["has_return_header"] = True
    row["ReturnHeader__json"] = json.dumps(rh_obj, ensure_ascii=False)
    row.update(flat)
    return row

def build_dataframe(input_dir: str) -> pd.DataFrame:
    rows = []
    for p in iter_xml_files(input_dir):
        try:
            rows.append(parse_return_header_row(p))
        except Exception as e:
            rows.append({
                "source_file": p,
                "has_return_header": False,
                "error": str(e),
            })
    return pd.DataFrame(rows)

# ---------------- Write to Delta table (Databricks / Spark) ----------------
def write_to_delta(pdf: pd.DataFrame, table: str, mode: str):
    sdf = spark.createDataFrame(pdf)  # spark must exist in Databricks
    (sdf.write
        .format("delta")
        .mode(mode)                 # "append" or "overwrite"
        .option("mergeSchema", "true")
        .saveAsTable(table)
    )

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input_dir", required=True, help="Directory containing .xml files (driver-visible path, e.g., /dbfs/...)")
    ap.add_argument("--table", default="irs_group_catalog.lakebase.xml_data", help="Target Delta table (Unity Catalog)")
    ap.add_argument("--mode", default="append", choices=["append", "overwrite"])
    args = ap.parse_args()

    pdf = build_dataframe(args.input_dir)
    write_to_delta(pdf, args.table, args.mode)

if __name__ == "__main__":
    main()
